#!/bin/sh

. /usr/share/debconf/confmodule

case "$1" in
  install|upgrade)
    if [ ! -z "$2" ]; then
      OLD_CCU_VERSION=`echo "$2" | sed 's/\([0-9]\+\.[0-9]\+\.[0-9]\+\)-[0-9]\+/\1/g'`

      if [ "{CCU_VERSION}" != "$OLD_CCU_VERSION" ]; then
        db_fset pivccu/has_backup seen false
        db_input critical pivccu/has_backup || true
        db_go

        db_get pivccu/has_backup
        if [ "$RET" = "false" ]; then
          db_input critical pivccu/err_no_backup || true
          db_go
          exit 2
        fi
      fi
    fi
    ;;
esac

