#!/bin/bash
. /usr/share/debconf/confmodule

set -e

case "$1" in
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    sed -i /var/lib/piVCCU/dtb/config.txt -e '/dtoverlay=pivccu-raspberrypi/d'
    umount /var/lib/piVCCU/dtb
    ;;

  purge)
    db_purge
  ;;
esac

