#!/bin/bash
. /usr/share/debconf/confmodule

set -e

case "$1" in
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    depmod -a {KERNEL_RELEASE}
    sed -i /boot/config.txt -e '/dtoverlay=pivccu-raspberrypi/d'
    ;;

  purge)
    db_purge
  ;;
esac

