#!/bin/bash

set -e

case "$1" in
  install|upgrade)
    dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo /boot/overlays/pivccu-raspberrypi.dtbo
    ;;

  abort-upgrade)
    ;;
esac

