#!/bin/bash

set -e

case "$1" in
  remove|upgrade|deconfigure)
    systemctl stop pivccu.service
    systemctl disable monitor-hb-rf-eth.service
    systemctl disable pivccu-startupfinished.service
    systemctl disable pivccu.service

    rm -f /usr/sbin/pivccu-attach
    rm -f /usr/sbin/pivccu-info
    rm -f /usr/sbin/pivccu-backup
    ;;

  failed-upgrade)
    ;;
esac
