#!/bin/sh

set -e

case "$1" in
  configure)
    if [ ! -e /pivccu.createimage ]; then
      /var/lib/piVCCU/dts/patch_dts.sh
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
esac


