#!/bin/bash
. /usr/share/debconf/confmodule

set -e

case "$1" in
  purge)
    db_purge
    rm -f /etc/default/hb_rf_eth
    ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
esac

