#!/bin/bash
. /usr/share/debconf/confmodule

function throw {
  echo $1
  exit 1
}

function run {
  echo -n "$1 ... "
  shift
  ERR=`$* 2>&1` && RC=$? || RC=$?
  if [ $RC -eq 0 ]; then
    echo -e "\033[0;32mDone\033[0;0m"
  else
    echo -e "\033[1;91mFAILED\033[0;0m"
    echo "$ERR"
    exit 1
  fi
}

case "$1" in
  purge)
    run "Cleanup debconf database" db_purge
    ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
esac

