#!/bin/bash
. /usr/share/debconf/confmodule

set -e

DKMS_VERSION={PKG_VERSION}

case "$1" in
  configure)
    if [ ! -e /pivccu.createimage ]; then
      dkms install -m pivccu -v $DKMS_VERSION -k `uname -r` || true
    fi

    systemctl enable pivccu-dkms.service

    if [ ! -e /pivccu.createimage ]; then
      db_fset pivccu/reboot_required seen false
      db_input medium pivccu/reboot_required || true
      db_go
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
esac
