#!/bin/bash

set -e

DKMS_VERSION={PKG_VERSION}

case "$1" in
  remove|upgrade|deconfigure)
    systemctl disable pivccu-dkms.service

    if [  "$(dkms status -m pivccu -v $DKMS_VERSION)" ]; then
      dkms remove -m pivccu -v $DKMS_VERSION --all
    fi
    ;;

  failed-upgrade)
    ;;
esac
