#!/bin/bash

set -e

DKMS_NAME=pivccu
DKMS_VERSION={PKG_VERSION}

case "$1" in
  remove|upgrade|deconfigure)
    systemctl disable pivccu-dkms.service

    if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
      dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
    fi
    ;;

  failed-upgrade)
    ;;
esac
