#!/bin/sh

HMRF_HARDWARE=`cat /sys/module/plat_eq3ccu2/parameters/board_extended_info | sed 1q | cut -d';' -f1`
HMIP_HARDWARE=`cat /sys/module/plat_eq3ccu2/parameters/board_extended_info | sed 1q | cut -d';' -f2`

start() {
  if [ ! -e /etc/config/no-coprocessor-update ] ; then
    case "$HMRF_HARDWARE" in
      "HM-MOD-RPI-PCB")
        echo "Checking if firmware Update is needed for HM-MOD-RPI-PCB" | logger -p user.info
        /bin/eq3configcmd update-coprocessor -p "/dev/mxs_auart_raw.0" -u -t HM-MOD-UART | logger -p user.info
        echo "update HM-MOD-RPI-PCB"
        ;;

      "RPI-RF-MOD")
        echo "Checking if firmware Update is needed for RPI-RF-MOD" | logger -p user.info
        /opt/jre-1.8.0_121-compact3/bin/java -Dgnu.io.rxtx.SerialPorts=/dev/mxs_auart_raw.0-jar /opt/HmIP/hmip-copro-update.jar -p /dev/mxs_auart_raw.0 -f /firmware/RPI-RF-MOD/dualcopro_update_blhmip-*.eq3 | logger -p user.info
        ;;
    esac

    case "$HMRF_HARDWARE" in
      "HMIP-RFUSB")
        echo "Checking if firmware Update is needed for HmIP-RFUSB" | logger -p user.info
        /opt/jre-1.8.0_121-compact3/bin/java -Dgnu.io.rxtx.SerialPorts=/dev/ttyS0-jar /opt/HmIP/hmip-copro-update.jar -p /dev/ttyS0 -f /firmware/HMIP-RFUSB/hmip_coprocessor_update-*.eq3 | logger -p user.info
        ;;
    esac
  fi
}

stop() {
  :
}

restart() {
  :
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

